- hosts: all
  become: yes
  gather_facts: no
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1dvars
  tasks:
  - name: "Updating via apt"
    apt:
      upgrade: yes
      update_cache: true
  
  - name: "Installing curl via apt"
    apt:
      name: curl
      state: present

  - name: "Installing UFW via apt"
    apt:
      name: ufs
      state: present
      
  - name: "Turning on UFW"
    ufw:
      state: enabled
      policy: allow
      
  - name: "Openning port 80"
    ufw:
      rule: allow
      port: '80'
      proto: tcp
      
  - name: "Openning port 8080"
    ufw:
      rule: allow
      port: '8080'
      proto: tcp
      
  - name: "Openning port 1834"
    ufw:
      rule: allow
      port: '80'
      proto: tcp
      
  - name: "Installing aptitude via apt"
    apt: 
      name: aptitude
      state: present
      update_cache: yes
    
  - name: "Installing required system packeges"
    apt:
      name: gpg apt-transport-https ca-certificates curl software-properties-common python3 python3-pip virtualenv python3-setuptools
      state: present
      update_cache: yes
    
  - name: "Adding gpg key for docker"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
       
  - name: "Add repos"
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
      
  - name: "Installing docker-ce"
    apt: 
      name: docker-ce
      state: latest
      update_cahe: yes
      
  - name: "Installing python modules"
    pip3:
      name: docker
