- hosts: all
  become: yes
  tasks:
  - name: "Updating via apt"
    apt:
      upgrade: yes
      update_cache: true
  
  - name: "Installing curl via apt"
    apt:
      name: curl
      state: present

  - name: "Installing UFW via apt"
    apt:
      name: ufs
      state: present
      
  - name: "Turning on UFW"
     community.general.ufw:
      state: enabled
      policy: allow
      
  - name: "Openning port 80"
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp
      
  - name: "Openning port 8080"
    community.general.ufw:
      rule: allow
      port: '8080'
      proto: tcp
      
  - name: "Openning port 1834"
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp

 - name: "Downloading and installing docker via officle script"
    shell: curl -fsSl https://get.docker.com -o get-docker.sh && DRY_RUN=1 sh./get-docker.sh
